### PR TITLE
add smoke test for ffjord

### PR DESCRIPTION
**Pull request by prbzrg**
I just added some smoke tests for ffjord to reveal errors related to some adtypes
It reveals errors that reported in #588, #610, #615, #624
This PR can be merged when these errors fixed

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Instead, just set `@test_broken` for now.

**Comment by prbzrg** [comment]
Should I expand the tests and unroll the loop?

**Comment by ChrisRackauckas** [comment]
Are all of the tests broken?

**Comment by prbzrg** [comment]
Regardless of `adtype`, using
```julia
regularize=true & monte_carlo=false
```
make errors and using
```julia
GalacticOptim.AutoForwardDiff()
GalacticOptim.AutoReverseDiff()
GalacticOptim.AutoTracker()
```
as `adtype` is also broken.
Overall, 14 of 20 tests are broken.

**Comment by ChrisRackauckas** [comment]
>as adtype is also broken.

What do you mean?

**Comment by prbzrg** [comment]
In each #610, #615, #624, I tested the same code with different `adtype` and reported errors.
`AutoZygote` and `AutoFiniteDiff` works fine, but other `adtype`s  make different errors.

**Comment by ChrisRackauckas** [comment]
oh with FFJORD, yes.

**Comment by ChrisRackauckas** [comment]
It looks like this still isn't catching some of the errors?

**Comment by prbzrg** [comment]
If we only use `@test`, it could reproduce all four issues, but also make testing fail, you can see the errors in CI of first commit:
https://github.com/SciML/DiffEqFlux.jl/runs/3628543892?check_suite_focus=true#step:6:312
https://github.com/SciML/DiffEqFlux.jl/runs/3628543892?check_suite_focus=true#step:6:636
https://github.com/SciML/DiffEqFlux.jl/runs/3628543892?check_suite_focus=true#step:6:969
https://github.com/SciML/DiffEqFlux.jl/runs/3628543892?check_suite_focus=true#step:6:1350

I think we have two choices:

1. Only use `@test` and wait until all four issues fixed to merge this.
2. Use both `@test` and `@test_broken` by unrolling the loop. We can merge this sooner, but it doesn't log errors to CI, and it increases line of codes (more code to read and review)

I don't know whether there is any other choices. By second one, if someone wants to fix the errors, just changes it to `@test` and investigate the problems, but I prefer shorter codes.
Which way should we go?

**Comment by ChrisRackauckas** [comment]
(2) is a better way to go, because it's always better to fix and change from broken than have things documented in unmerged PRs.

**Comment by prbzrg** [comment]
OK, I made the loop unrolled and also converted section comments to `testset`s.
Furthermore, I notice something; there is a test for FFJORD with regularizers
https://github.com/SciML/DiffEqFlux.jl/blob/34c022fe0a829ad5a54499d8aa97355ecadb6e36/test/cnf_test.jl#L103-L127
but it doesn't use `regularize=true`!

**Comment by prbzrg** [comment]
I want to update other tests to more look like tests of this PR:

1. Use `Float32` distribution instead of converting samples 
2. Use `DiffEqFlux.sciml_train` instead of `OptimizationFunction -> OptimizationProblem -> solve`

Can I update other tests in this PR?

**Comment by prbzrg** [comment]
I made the updates. If you disagree, I will move them to new PR.

**Comment by prbzrg** [comment]
Tests are failing. I just undo two last commits and will change other tests in a new PR.

**Comment by ChrisRackauckas** [comment]
Thanks!

**Pull request merged**
