### PR TITLE
Require Zygote 0.5

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
This is required in order to have the right overloads for FFJORD

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
```julia
MethodError: no method matching +(::NamedTuple{(:dim, :mat, :chol),Tuple{Nothing,Nothing,NamedTuple{(:uplo, :info, :factors),Tuple{Nothing,Nothing,UpperTriangular{Float64,Array{Float64,2}}}}}}, ::Array{Float64,2})
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:529
  +(!Matched::ChainRulesCore.DoesNotExist, ::Any) at C:\Users\accou\.julia\packages\ChainRulesCore\7m6Ti\src\differential_arithmetic.jl:22
  +(!Matched::ChainRulesCore.One, ::Any) at C:\Users\accou\.julia\packages\ChainRulesCore\7m6Ti\src\differential_arithmetic.jl:83
  ...
accum(::NamedTuple{(:dim, :mat, :chol),Tuple{Nothing,Nothing,NamedTuple{(:uplo, :info, :factors),Tuple{Nothing,Nothing,UpperTriangular{Float64,Array{Float64,2}}}}}}, ::Array{Float64,2}) at lib.jl:8
macro expansion at lib.jl:19 [inlined]
accum(::NamedTuple{(:μ, :Σ),Tuple{Array{Float64,1},NamedTuple{(:dim, :mat, :chol),Tuple{Nothing,Nothing,NamedTuple{(:uplo, :info, :factors),Tuple{Nothing,Nothing,UpperTriangular{Float64,Array{Float64,2}}}}}}}}, ::NamedTuple{(:μ, :Σ),Tuple{Nothing,Array{Float64,2}}}) at lib.jl:19
getindex at tuple.jl:24 [inlined]
gradindex at reverse.jl:12 [inlined]
_logpdf at mvnormal.jl:127 [inlined]
(::typeof(∂(_logpdf)))(::Float64) at interface2.jl:0
_pdf at multivariates.jl:190 [inlined]
(::typeof(∂(_pdf)))(::Float64) at interface2.jl:0
pdf at multivariates.jl:201 [inlined]
(::typeof(∂(pdf)))(::Float64) at interface2.jl:0
FFJORD at ffjord.jl:87 [inlined]
(::typeof(∂(λ)))(::Float64) at interface2.jl:0
FFJORD at ffjord.jl:80 [inlined]
(::typeof(∂(λ)))(::Float64) at interface2.jl:0
#11 at none:0 [inlined]
(::typeof(∂(λ)))(::Float64) at interface2.jl:0
#589 at array.jl:182 [inlined]
#3 at generator.jl:36 [inlined]
iterate at generator.jl:47 [inlined]
collect(::Base.Generator{Base.Iterators.Zip{Tuple{Array{typeof(∂(λ)),1},Array{Float64,1}}},Base.var"#3#4"{Zygote.var"#589#593"}}) at array.jl:665
map at abstractarray.jl:2154 [inlined]
(::Zygote.var"#588#592"{Array{typeof(∂(λ)),1}})(::Array{Float64,1}) at array.jl:182
(::Zygote.var"#616#617"{Zygote.var"#588#592"{Array{typeof(∂(λ)),1}}})(::Array{Float64,1}) at array.jl:198
loss_adjoint at cnf_test.jl:25 [inlined]
(::typeof(∂(loss_adjoint)))(::Float64) at interface2.jl:0
#179 at lib.jl:178 [inlined]
(::Zygote.var"#1720#back#181"{Zygote.var"#179#180"{typeof(∂(loss_adjoint)),Tuple{Tuple{Nothing},Tuple{}}}})(::Float64) at adjoint.jl:49
#49 at train.jl:99 [inlined]
(::typeof(∂(λ)))(::Float64) at interface2.jl:0
(::Zygote.var"#54#55"{Zygote.Params,Zygote.Context,typeof(∂(λ))})(::Float64) at interface.jl:177
gradient(::Function, ::Zygote.Params) at interface.jl:54
macro expansion at train.jl:98 [inlined]
macro expansion at ProgressLogging.jl:328 [inlined]
(::DiffEqFlux.var"#48#53"{typeof(cb),Int64,Bool,Bool,typeof(loss_adjoint),Array{Float32,1},Zygote.Params})() at train.jl:43
maybe_with_logger(::DiffEqFlux.var"#48#53"{typeof(cb),Int64,Bool,Bool,typeof(loss_adjoint),Array{Float32,1},Zygote.Params}, ::Nothing) at utils.jl:259
sciml_train(::Function, ::Array{Float32,1}, ::ADAM, ::Base.Iterators.Cycle{Tuple{DiffEqFlux.NullData}}; cb::Function, maxiters::Int64, progress::Bool, save_best::Bool) at train.jl:42
sciml_train at train.jl:77 [inlined]
(::DiffEqFlux.var"#sciml_train##kw")(::NamedTuple{(:cb, :maxiters),Tuple{typeof(cb),Int64}}, ::typeof(DiffEqFlux.sciml_train), ::Function, ::Array{Float32,1}, ::ADAM) at train.jl:77
top-level scope at cnf_test.jl:29
```

@DhairyaLGandhi do you know of a change in Zygote that could've caused this? Or is this a DistributionsAD thing? (maybe @devmotion?). It was working just a week ago or so.

**Comment by devmotion** [comment]
Maybe it's related to the ChainRules support in Zygote 0.5 (but Zygote 0.5 was supported before, wasn't it?)? BTW why is DistributionsAD needed here?

**Comment by ChrisRackauckas** [comment]
>BTW why is DistributionsAD needed here?

I don't know 😆 I'm just trying to figure out why differentiating through the MVNormal logpdf isn't working anymore. Thought I'd give it a try.

**Comment by ChrisRackauckas** [comment]
@avik-pal @d-netto let me know if you found any leads on this error.

**Comment by avik-pal** [comment]
It seems the issue arrises from using `log(pdf(dist, z))`. If we use `logpdf(dist, z)` then the issue is solved for this MWE
```julia
dist = MvNormal(rand(1), I + zeros(1, 1))
z = zeros(1)

Zygote.gradient(z -> log(pdf(dist, z)), z) # fails
Zygote.gradient(z -> logpdf(dist, z), z) # works
```

**Comment by d-netto** [comment]
I couldn't reproduce it in my machine: both are throwing errors for me.

**Comment by avik-pal** [comment]
```
Status `~/.julia/environments/v1.5/Project.toml`
  [aae7a2af] DiffEqFlux v1.17.0 `https://github.com/SciML/DiffEqFlux.jl.git#ChrisRackauckas-patch-1`
  [31c24e10] Distributions v0.23.5
  [ced4e74d] DistributionsAD v0.6.2
  [587475ba] Flux v0.11.0
  [1dea7af3] OrdinaryDiffEq v5.42.0
  [9f7883ad] Tracker v0.2.8
  [e88e6eb3] Zygote v0.5.3
```

**Comment by ChrisRackauckas** [comment]
There still seems to be a remaining issue?

**Comment by avik-pal** [comment]
Changing the sensealg fixes FFJORD for me
```julia
function (n::FFJORD)(x,p=n.p,monte_carlo=n.monte_carlo)
    e = monte_carlo ? randn(Float32,length(x)) : nothing
    ffjord_ = (du,u,p,t)->ffjord(du,u,p,t,n.re,monte_carlo,e)
    prob = ODEProblem{true}(ffjord_,vcat(x,0f0),n.tspan,p)
    sense = InterpolatingAdjoint(autojacvec = false)
    pred = solve(prob,n.args...;sensealg = sense,n.kwargs...)[:,end]
    pz = n.basedist
    z = pred[1:end-1]
    delta_logp = pred[end]
    logpz = logpdf(pz, z)
    logpx = logpz .- delta_logp
    return logpx[1]
end
```

**Comment by ChrisRackauckas** [comment]
we don't want to do that long term, but to stop the current issue I'm going to do that an open an issue about the AD regression.

**Pull request merged**
