### PR TITLE
Default allow_f_increases=true

### PR DESCRIPTION
**Pull request by YingboMa**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@ranjanan opinion here?

**Comment by ranjanan** [comment]
Fantastic!

**Comment by ChrisRackauckas** [comment]
From the tests, it seems that if we do this the optimization never haults, so we may just want to make this a well-known argument but not a default? Or if it is a default, require maxiters?

**Comment by ranjanan** [comment]
Let's not make it a default. Yes, if it's supplied, you must also enter a maxiters. Using this option can be a recommended experiment. Worse case the loss blows up and we can discard it.

**Comment by ChrisRackauckas** [comment]
Losses going to 1e-82 is absolutely fantastic though :P

**Pull request closed without merging**
