### PR TITLE
docs: run all the example blocks and clean up a few things

### PR DESCRIPTION
**Pull request by sathvikbhagavan**
Noticed a few examples were not run in the doc build.

## Checklist

- [x] Appropriate tests were added
- [x] Any code changes were done in a way that does not break public API
- [x] All documentation related to code changes were updated
- [x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [x] Any new documentation only uses public API

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Awesome, some failures and a ways to go but yes we really needed this https://buildkite.com/julialang/diffeqflux-dot-jl/builds/1488#018c7825-2cbf-4e04-b151-d3012c1560d4

**Comment by sathvikbhagavan** [comment]
ok, I will look into the failures

**Comment by sathvikbhagavan** [comment]
@ChrisRackauckas, I have fixed most of them but there are two failures:

1. Neural ODE on GPUs - https://buildkite.com/julialang/diffeqflux-dot-jl/builds/1490#018c7c0f-673d-4cf5-b19c-b5f4279b054e/1071-1286 
2. Neural SDE - https://buildkite.com/julialang/diffeqflux-dot-jl/builds/1490#018c7c0f-673d-4cf5-b19c-b5f4279b054e/1071-3521

Any ideas on what's causing this? 

I haven't changed anything on Neural SDE one and its still failing (but passing on master), so it can be some upstream issue.

**Comment by ChrisRackauckas** [comment]
I thought @avik-pal had recently gone through and fixed all of the docs examples, so I'll let him comment.

**Comment by avik-pal** [comment]
Could https://buildkite.com/julialang/diffeqflux-dot-jl/builds/1490#018c7c0f-673d-4cf5-b19c-b5f4279b054e/1071-1341 have something to do with the recent RAT update? On master build seems to be fine

**Comment by avik-pal** [comment]
The NeuralSDE one is quite strange, it passes on 1.10 but sometimes failed on 1.9. I can take a look at it later today to confirm

**Comment by avik-pal** [comment]
Oh I see. I will take a look

**Comment by avik-pal** [comment]
@sathvikbhagavan https://github.com/SciML/DiffEqFlux.jl/pull/890 fixes the problem. But probably something is generating too many plots and hence the build is not going through. can you take a look at that?

**Comment by sathvikbhagavan** [comment]
>But probably something is generating too many plots and hence the build is not going through. can you take a look at that?

Yes, I will look in it

**Comment by sathvikbhagavan** [comment]
@avik-pal can you merge/make a PR using the branch in https://github.com/SciML/DiffEqFlux.jl/pull/890 into my branch here? I think I know what is the issue and will fix that

**Comment by ChrisRackauckas** [comment]
I just merged it to master. Start fresh from master and just make the change there.

**Pull request merged**
