### PR TITLE
Fix "dense.W" deprecation warning

### PR DESCRIPTION
**Pull request by prbzrg**
Fixes this warning:
```julia
field name dense.W is deprecated in favour of dense.weight
```

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
Up the lower bound?

**Comment by prbzrg** [comment]
From Flux.jl `news.md` file for version 0.12.0:
```julia
End of deprecation cycle: loss functions cannot be accessed directly from Flux anymore, they live in the Flux.Losses module. All loss functions perform mean aggregation by default.
```

These lines can make errors:
https://github.com/SciML/DiffEqFlux.jl/blob/bb8ea2c2133d3df5c560fdbc5962ffe0c25dbee6/test/newton_neural_ode.jl#L24

https://github.com/SciML/DiffEqFlux.jl/blob/bb8ea2c2133d3df5c560fdbc5962ffe0c25dbee6/test/newton_neural_ode.jl#L38

Should I fix these lines too?

**Comment by ChrisRackauckas** [comment]
Yes please.

**Comment by prbzrg** [comment]
Ok, done.

**Pull request merged**
