### PR TITLE
Neural ODE tutorial

### PR DESCRIPTION
**Pull request by Abhishek-1Bhatt**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
oh no test failure 😅 but might as well get this out there.

**Comment by Abhishek-1Bhatt** [comment]
My very not nefarious pr 😅

**Comment by ChrisRackauckas** [comment]
Oh it's the Lux v1.6 thing

**Comment by ChrisRackauckas** [comment]
@avik-pal 😢

**Comment by ChrisRackauckas** [comment]
Should be fixed now 🎉

**Pull request merged**
